branches:
  only:
  - master

arch:
  - amd64

os: linux

dist: bionic

env:
  global:
    - REPO_MAKE_CACHE=$HOME/cache
    - REPO_MAKE_TARGET=$HOME/repo
    - REPO_MAKE_PKGBUILDS=$TRAVIS_BUILD_DIR
  jobs:
    - REPO_MAKE_ARCH=x86_64
      REPO_MAKE_MAKEPKG_CONF=./.ci/makepkg.conf
    - REPO_MAKE_ARCH=armv7h
      REPO_MAKE_MAKEPKG_CONF=./.ci/makepkg-armv7h.conf

language: generic

git:
  quiet: true

cache:
  directories:
    - $HOME/cache

before_script:
  - git clone https://github.com/VDR4Arch/$REPO_MAKE_ARCH.git --branch master --single-branch $HOME/repo || true
  - rm -rf $HOME/repo/.git

script:
  - sudo ./.ci/repo-make-ci.sh

before_deploy:
  - sudo chown -R $USER:$USER $HOME/repo
  - ./.ci/genindex.sh $HOME/repo $REPONAME

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: $HOME/repo/
  repo: VDR4Arch/$REPO_MAKE_ARCH
  target_branch: master
  on:
    repo: $TRAVIS_REPO_SLUG
    branch: master
