branches:
  only:
  - master

arch:
  - arm64

os: linux

dist: bionic

env:
  global:
    - REPO_MAKE_CACHE=$HOME/cache
    - REPO_MAKE_TARGET=$HOME/repo
    - REPO_MAKE_PKGBUILDS=$TRAVIS_BUILD_DIR
    - REPO_MAKE_ARCH=armv7h

language: generic

git:
  quiet: true

cache:
  directories:
    - $HOME/cache

before_script:
  - rm -rf $HOME/repo/.git

script:
  - sudo ./.ci/repo-make-ci.sh

